server:
  cors:
    origin: http://localhost:8080
clients:
  auth:
    baseUrl: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/v1/auth
  profile:
    baseUrl: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/v1/users